version: '3'
services:
  #app:
  #  build: ./app
  #  ports:
  #    - 3000:3000
  #  depends_on:
  #    - database
  #    - elasticsearch
  #    - nominatim
  #  networks:
  #    - realassistant-network
  database:
    build: ./database
    ports:
      - "5432:5432"
    env_file:
      - app/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - realassistant-network-local
  opensearch-node:
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch-node
    environment:
      - "cluster.name=opensearch-cluster"
      - "node.name=opensearch-node"
      - "discovery.type=single-node"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-methods: OPTIONS,HEAD,GET,POST,PUT,DELETE"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
      - "bootstrap.memory_lock=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - realassistant-network-local
  section-identifier:
    build: ./section-identifier
    ports:
      - "8080:80"
    # environment:
    #   - ENV_VAR_NAME=env_var_value
    networks:
      - realassistant-network-local

  # opensearch-dashboards:
  #   image: opensearchproject/opensearch-dashboards:2.12.0
  #   container_name: opensearch-dashboards
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - 'OPENSEARCH_HOSTS=["http://opensearch-node:9200"]'
  #     - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
  #   networks:
  #     - realassistant-network


  # nominatim:
  #   image: mediagis/nominatim:4.2
  #   container_name: nominatim
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - PBF_URL=https://download.geofabrik.de/north-america/us-latest.osm.pbf
  #     - REPLICATION_URL=https://download.geofabrik.de/north-america/us-updates/
  #     - IMPORT_WIKIPEDIA=false
  #     - NOMINATIM_PASSWORD=very_secure_password
  #   volumes:
  #     - nominatim-data:/var/lib/postgresql/14/main
  #   networks:
  #     - realassistant-network
  #   shm_size: '1g'


  #libpostal:
  #  build: ./libpostal-rest-docker
  #  ports:
  #    - 8222:8080
  #  networks:
  #    - realassistant-network

volumes:
  postgres-data:
  opensearch-data:
    #nominatim-data:    

networks:
  realassistant-network-local:
    name: realassistant-network-local